//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сourier.AccounterReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccounterReference.IAccountant")]
    public interface IAccountant {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountant/GetPrice", ReplyAction="http://tempuri.org/IAccountant/GetPriceResponse")]
        int GetPrice(int productID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountant/GetPrice", ReplyAction="http://tempuri.org/IAccountant/GetPriceResponse")]
        System.Threading.Tasks.Task<int> GetPriceAsync(int productID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountant/LogResult", ReplyAction="http://tempuri.org/IAccountant/LogResultResponse")]
        void LogResult(string productName, int quantity, bool success);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountant/LogResult", ReplyAction="http://tempuri.org/IAccountant/LogResultResponse")]
        System.Threading.Tasks.Task LogResultAsync(string productName, int quantity, bool success);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountantChannel : Сourier.AccounterReference.IAccountant, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountantClient : System.ServiceModel.ClientBase<Сourier.AccounterReference.IAccountant>, Сourier.AccounterReference.IAccountant {
        
        public AccountantClient() {
        }
        
        public AccountantClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountantClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountantClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountantClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetPrice(int productID, int quantity) {
            return base.Channel.GetPrice(productID, quantity);
        }
        
        public System.Threading.Tasks.Task<int> GetPriceAsync(int productID, int quantity) {
            return base.Channel.GetPriceAsync(productID, quantity);
        }
        
        public void LogResult(string productName, int quantity, bool success) {
            base.Channel.LogResult(productName, quantity, success);
        }
        
        public System.Threading.Tasks.Task LogResultAsync(string productName, int quantity, bool success) {
            return base.Channel.LogResultAsync(productName, quantity, success);
        }
    }
}
