//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.CourierServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourierServiceReference.ICourier")]
    public interface ICourier {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourier/TakeGoods", ReplyAction="http://tempuri.org/ICourier/TakeGoodsResponse")]
        void TakeGoods(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourier/TakeGoods", ReplyAction="http://tempuri.org/ICourier/TakeGoodsResponse")]
        System.Threading.Tasks.Task TakeGoodsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourier/TestConnect", ReplyAction="http://tempuri.org/ICourier/TestConnectResponse")]
        void TestConnect(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourier/TestConnect", ReplyAction="http://tempuri.org/ICourier/TestConnectResponse")]
        System.Threading.Tasks.Task TestConnectAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourierChannel : Manager.CourierServiceReference.ICourier, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourierClient : System.ServiceModel.ClientBase<Manager.CourierServiceReference.ICourier>, Manager.CourierServiceReference.ICourier {
        
        public CourierClient() {
        }
        
        public CourierClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourierClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourierClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourierClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TakeGoods(int id) {
            base.Channel.TakeGoods(id);
        }
        
        public System.Threading.Tasks.Task TakeGoodsAsync(int id) {
            return base.Channel.TakeGoodsAsync(id);
        }
        
        public void TestConnect(string str) {
            base.Channel.TestConnect(str);
        }
        
        public System.Threading.Tasks.Task TestConnectAsync(string str) {
            return base.Channel.TestConnectAsync(str);
        }
    }
}
